version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./BackEnd_nodejs
      dockerfile: Dockerfile
    container_name: servo-msg-backend
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # 前端服务
  frontend:
    build:
      context: ./FrontEnd_Vue3
      dockerfile: Dockerfile
    container_name: servo-msg-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
