version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./BackEnd_nodejs
      dockerfile: Dockerfile
    container_name: servo-msg-backend-dev
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

  # 前端服务（开发模式）
  frontend-dev:
    build:
      context: ./FrontEnd_Vue3
      dockerfile: Dockerfile.dev
    container_name: servo-msg-frontend-dev
    ports:
      - "8002:8002"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./FrontEnd_Vue3/src:/app/src
      - ./FrontEnd_Vue3/public:/app/public

networks:
  app-network:
    driver: bridge
